from django.urls import path

from .views import (
    CadastroUsuarioView,
    ChangePasswordView,
    ForgotPasswordView,
    LoginUsuarioView,
    LogoutUsuarioView,
    MeView,
    OnboardingUsuarioView,
    RefreshUsuarioView,
    ResetPasswordView,
    UsuarioDetailView,
)
from .domain_views import (
    AdminActionsView,
    AdminCommunityPostsView,
    AdminMetricsView,
    AdminProfessionalVerificationDetailView,
    AdminProfessionalVerificationsView,
    CheckInDetailView,
    CheckInListView,
    CheckInSummaryView,
    CommentFeedbackView,
    CommunityCommentCreateView,
    CommunityPostDetailView,
    CommunityPostsView,
    CommunitySupportView,
    ContentDetailView,
    ContentsListView,
    NotificationPreferencesView,
    NotificationDispatchView,
    NotificationSubscriptionView,
    PrivacyDeleteRequestView,
    PrivacyExportView,
    RecommendationsView,
    UserAvatarUploadView,
)


urlpatterns = [
    path("cadastro/", CadastroUsuarioView.as_view(), name="api_cadastro"),
    path("login/", LoginUsuarioView.as_view(), name="api_login"),
    path("password/forgot/", ForgotPasswordView.as_view(), name="api_password_forgot"),
    path("password/reset/", ResetPasswordView.as_view(), name="api_password_reset"),
    path("password/change/", ChangePasswordView.as_view(), name="api_password_change"),
    path("refresh/", RefreshUsuarioView.as_view(), name="api_refresh"),
    path("logout/", LogoutUsuarioView.as_view(), name="api_logout"),
    path("me/", MeView.as_view(), name="api_me"),
    path("check-ins/", CheckInListView.as_view(), name="api_check_ins"),
    path("check-ins/summary/", CheckInSummaryView.as_view(), name="api_check_ins_summary"),
    path("check-ins/<str:check_in_id>/", CheckInDetailView.as_view(), name="api_check_in_detail"),
    path("contents/", ContentsListView.as_view(), name="api_contents"),
    path("contents/<str:content_id>/", ContentDetailView.as_view(), name="api_content_detail"),
    path("recommendations/", RecommendationsView.as_view(), name="api_recommendations"),
    path("community/posts/", CommunityPostsView.as_view(), name="api_community_posts"),
    path("community/posts/<str:post_id>/", CommunityPostDetailView.as_view(), name="api_community_post_detail"),
    path(
        "community/posts/<str:post_id>/comments/",
        CommunityCommentCreateView.as_view(),
        name="api_community_post_comments",
    ),
    path(
        "community/posts/<str:post_id>/support/",
        CommunitySupportView.as_view(),
        name="api_community_post_support",
    ),
    path(
        "community/comments/<str:comment_id>/feedback/",
        CommentFeedbackView.as_view(),
        name="api_community_comment_feedback",
    ),
    path("notifications/preferences/", NotificationPreferencesView.as_view(), name="api_notification_preferences"),
    path("notifications/subscriptions/", NotificationSubscriptionView.as_view(), name="api_notification_subscriptions"),
    path("notifications/dispatch-daily-check-ins/", NotificationDispatchView.as_view(), name="api_notification_dispatch_daily"),
    path("admin/metrics/", AdminMetricsView.as_view(), name="api_admin_metrics"),
    path("admin/actions/", AdminActionsView.as_view(), name="api_admin_actions"),
    path(
        "admin/professional-verifications/",
        AdminProfessionalVerificationsView.as_view(),
        name="api_admin_professional_verifications",
    ),
    path(
        "admin/professional-verifications/<str:verification_id>/",
        AdminProfessionalVerificationDetailView.as_view(),
        name="api_admin_professional_verification_detail",
    ),
    path("admin/community/posts/", AdminCommunityPostsView.as_view(), name="api_admin_community_posts"),
    path(
        "admin/community/posts/<str:post_id>/",
        CommunityPostDetailView.as_view(),
        name="api_admin_community_post_detail",
    ),
    path("privacy/export/", PrivacyExportView.as_view(), name="api_privacy_export"),
    path("privacy/delete-request/", PrivacyDeleteRequestView.as_view(), name="api_privacy_delete_request"),
    path("usuario/<str:uid>/avatar/", UserAvatarUploadView.as_view(), name="api_usuario_avatar"),
    path("usuario/<str:uid>/onboarding/", OnboardingUsuarioView.as_view(), name="api_usuario_onboarding"),
    path("usuario/<str:uid>/", UsuarioDetailView.as_view(), name="api_usuario_detail"),
]
